### ISSUE TITLE
Can you provide the TnpB sequence？

### ISSUE THREAD

**Issue by bioshendi** [Zhanglab-IOZ/TnpB#3]
Hello, I run the script to obtain the TnpB sequence identified in the article, but I have encountered problems. Is it convenient to provide the TnpB sequence identified in the article? Thank you

**Comment by li-yq** [comment]
TnpB sequences from both ISFinder and our *de novo* annotation is available in [Supplementary Table 6](https://www.nature.com/articles/s41587-023-01857-x#Sec53). Is that what you want?

**Comment by bioshendi** [comment]
What I need is 11531 tnpB loci mentioned in the article. can  you provide it? Thank you

**Comment by bioshendi** [comment]
![image](https://github.com/user-attachments/assets/6b7a9aa8-6422-4369-861c-8ed27ca69e9f)

**Comment by li-yq** [comment]
To save storage space, we didn't extract all the TnpB protein sequences; we only have the filtered ones at hand. If you need the complete set of TnpB sequences, you'll need to filter them from the NCBI gene annotations files based on the HMMER search results. You don't even need to run the entire workflow; a manual HMMER search will suffice. What specific problems are you encountering?

BTW, if you just need some TnpB sequences, you may also refer to other works on TnpB diversity (e.g., 10.1073/pnas.2308224120, 10.3390/genes14020523).

**Comment by bioshendi** [comment]
Thank you very much. I need to search for TnpB from the genome to extract the protein sequence, but I am not clear about which genomic data of NCBI should be used, and whether the result of merged_tnpb.faa is the file where all TnpB sequences are located.

**Comment by li-yq** [comment]
`merged_tnpb.faa` contains both newly discovered TnpBs and previous known TnpBs (from ISfinder), they are merged together and clustered to select TnpBs that are not clustered with known ones.

For all protein sequences before clustering, you can use the `results/genomes/{genome}/tnpb.faa`.

**Comment by bioshendi** [comment]
Okay, thank you very much.

**Comment by bioshendi** [comment]
Thank you so very much. I have revised the Snakefile. Would it be possible for you to offer the filtered sequence after the filtering? I would be extremely grateful.

**Comment by li-yq** [comment]
[Here] are the clustering results and the representative TnpB sequences. Accessions codes for all 11531 hits are also provided in the table. 

[Here]: https://gist.github.com/li-yq/477091aefeffd3a726e86845c98e409d

**Comment by bioshendi** [comment]
Thank you very much for your help and patience.
